name: CI Pipeline for Infrastructure

on:
  push:
    branches:
      - main
      - feature/*

jobs:
    build:
      runs-on: ubuntu-latest
      environment: dev
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: check dir after setting working-dir
          working-directory: environments/dev
          run: |
            echo "setting up env variables"
            echo "ARM_SUBSCRIPTION_ID=${{secrets.SUBSCRIPTION_ID}}" >> $GITHUB_ENV
            echo "ARM_TENANT_ID=${{secrets.TENANTID}}" >> $GITHUB_ENV
            echo "ARM_CLIENT_ID=${{secrets.CLIENT_ID}}" >> $GITHUB_ENV
            echo "ARM_CLIENT_SECRET=${{secrets.CLIENT_SECRET}}" >> $GITHUB_ENV
            echo "TF_VAR_subscription_id=${{secrets.SUBSCRIPTION_ID}}" >> $GITHUB_ENV
            
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v1
         
        - name: Terraform Init
          working-directory: environments/dev
          run: terraform init

        - name: Terraform Validate
          working-directory: environments/dev
          run: terraform validate

        - name: Terraform Plan
          working-directory: environments/dev
          run:  terraform plan -out main.tfplan 

        - name: Terraform Apply
          working-directory: environments/dev
          run: terraform apply main.tfplan

    