name: CI Pipeline for Infrastructure

on:
  push:
    branches:
      - main
      - feature/*

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: dir
          run: ls -la

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v1
         
        - name: Terraform Init
          run: terraform init

        - name: Terraform Validate
          run: terraform validate

        - name: Terraform Plan
          run: terraform plan

    